# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      # Runs a single command using the runners shell
      - name: Test demultiplex masks
        run: testPipeline/templates/demultiplex/demultiplex_test.sh

      - name: Test Run Parameters
        run: cd ./bin/test && python test_generate_run_params.py

      - name: Test Barcode Collision Detection
        run: cd ./bin/test && python test_detect_barcode_collision.py

      - name: Test split samplesheet
        run: pip install pandas && ./bin/test/test_split_sample_sheet.sh

      - name: Test cellranger outputs
        run: testPipeline/templates/cellranger/cellranger_test.sh

      - name: samplesheet_stats_main_test HWG
        run: >
          ./testPipeline/create_local_executor_config.sh nextflow.config &&
          cd testPipeline &&
          docker build -t nf-fastq-plus-playground . > /dev/null &&
          docker run -v /home/runner/work/nf-fastq-plus/nf-fastq-plus:/nf-fastq-plus nf-fastq-plus-playground

      - name: demux test
        run: >
          cd testPipeline &&
          docker run --entrypoint /nf-fastq-plus/testPipeline/e2e/cellranger_demux_stats.sh -v $(pwd)/../../nf-fastq-plus:/nf-fastq-plus nf-fastq-plus-playground
